parameters:
#    mb_site.example.class: MB\Bundle\SiteBundle\Example

services:
#    mb_site.example:
#        class: %mb_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
